title = "Griffin Painting"
description = "The Top Vancouver Island Painting & Pressure Washing Services. Get a free no contact estimate. Book online or call today! Our professional painters are ready to transform your home or business."
languageCode = "en-ca"
baseURL = "https://www.griffinpainting.ca/"
DefaultContentLanguage = "en"
disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]

[params]
gtm = "GTM-NBDLGX3"
servicename = "ProfessionalService"
googlemap = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1324266.1190198846!2d-126.9693421123112!3d49.58912588292742!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x5488135e104bec87%3A0xc935ddf37994210c!2sGriffin%20Painting!5e0!3m2!1sen!2sca!4v1635169493264!5m2!1sen!2sca"
sitename = "Griffin Painting"
usebasin = "https://usebasin.com/f/5b971a10c9a5"
videoOn = true
description = "The Top Vancouver Island Painting & Pressure Washing Services. Get a free no contact estimate. Book online or call today! Our professional painters are ready to transform your home or business."

[params.schema]
ogimage = "https://imagedelivery.net/55TzV2Sm0ZC5Gj13gsciyw/524d48e7-fa7a-402b-cec1-2ff38d4e9b00/FullBackgroundDesktop"
logofooter = "https://imagedelivery.net/55TzV2Sm0ZC5Gj13gsciyw/508325bb-c6c5-4b21-3456-c5c963791100/SquareDesktop"
city = "Ucluelet"
logo = "https://imagedelivery.net/55TzV2Sm0ZC5Gj13gsciyw/508325bb-c6c5-4b21-3456-c5c963791100/public"
reservation = true
phone = "+1-250-661-4535"
priceRange = "$$$"
region = "BC"
country = "Canada"
postalcode = "V0R 3A0"
type = "ProfessionalService"
openinghour = "Mo-Su"
email = "kyle@griffinpainting.ca"
address1 = "#"
address2 = "#"
address_toggle = false

[params.social]
facebook = "https://www.facebook.com/Griffin-Painting-102005895302182"
twitter = "#"
pinterest = "#"
instagram = "https://www.instagram.com/griffinpaintingltd"
linkedin = "#"

[[params.hours]]
hours = "Mon to Fri: 8AM to 7PM"

[[params.hours]]
hours = "Tue: 8AM to 7PM"

[[params.hours]]
hours = "Sat: 8AM to 7PM"

[[params.hours]]
hours = "Sun: 8AM to 7PM"

[module]

[[module.mounts]]
source = "assets"
target = "assets"

[[module.mounts]]
source = "./node_modules/alpinejs/dist/alpine.js"
target = "assets/js/alpine.js"

[[module.mounts]]
source = "./node_modules/lazysizes/lazysizes.js"
target = "assets/js/lazysizes.js"

[[module.mounts]]
source = "./node_modules/aos/dist/aos.js"
target = "assets/js/aos.js"

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5

[build]
writeStats = true
enableRobotsTXT = true

[menu]

[[menu.main]]
name = "Home"
url = "/"
weight = "1"

[[menu.main]]
name = "About"
url = "about/"
weight = "2"

[[menu.main]]
name = "Gallery"
url = "gallery/"
weight = "3"

[[menu.main]]
name = "Services"
url = "services/"
weight = "4"

[[menu.main]]
name = "Contact"
url = "contact/"
weight = "5"

[[menu.main]]
name = "Get A Quote"
url = "quote/"
weight = "6"